# Generated by Django 2.2.6 on 2019-11-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='department',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='organizer',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
